application: edutry1
version: 1
# version: 0-philipp
# version: 3-ralph-with-languagecount-support
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# css files
- url: /static
  static_dir: static
- url: /docs
  static_dir: docs
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /try-it
  static_dir: try-it
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  script: main.app
  
- url: /(home|users/join|about|contact).*
  script: main.app

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: markupsafe                                                              
  version: latest 

builtins:
- remote_api: on
